version: '2'
services:
  metrics-data:
    build: metrics-data
  metrics:
    build: .
    volumes_from: 
      - metrics-data
    ports:
      - "80:80"
      - "3000:3000"
      - "2003:2003"
      - "2004:2004"
      - "7002:7002"
      - "8125:8125/udp"
      - "8126:8126"
